name: CICD using Git actions and heroku

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: chechout
        uses: actions/checkout@v3
      - name: raie pr
        run: bash ./script.bash ${{secrets.git_token}}
